version: "3"

services:

  nginx:
    container_name: nginx_container
    build:
      context: nginx/
      dockerfile: Dockerfile
    restart: always
    expose:
      - 80
    ports:
      - 80:80
    networks:
      - app_network

  db:
    container_name: db_container
    build:
      context: ./postgis
      dockerfile: Dockerfile
    env_file:
      - .env-local
    ports:
      - 5432:5432
    volumes:
      - ./postgis/data/db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app_network

  app:
    container_name: app_container
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - .env-local
    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - ./app/bamapas:/opt/app
    depends_on:
      - db
    networks:
      - app_network
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - .env-local
    ports:
      - 5000:80
    depends_on:
      - db
    networks:
      - app_network

  redis:
    container_name: redis_container
    image: redis
    ports:
      - 6379:6379
    depends_on:
      - app
    networks:
      - app_network
      
networks:
  app_network:
    driver: bridge

volumes:
    db:
    app: