services:

  db:
    container_name: db_container
    build:
      context: ./postgis
      dockerfile: Dockerfile
    env_file:
      - .env    
    ports:
      - "5444:5432"    
    volumes:
      - ./postgresql/data/db:/var/lib/postgresql/data
    restart: unless-stopped
    #command: >
      #- psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f opt/db_dump/componentes.sql
      #- psql -U ${POSTGRES_USER} -h ${POSTGRES_HOST} -d ${POSTGRES_DB} -f /db_dump/componentes.sql
    networks:
      - db_network

  app:
    container_name: app_container
    build:
      context: ./app
      dockerfile: Dockerfile
    # command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - /bamapas:/opt/app
    depends_on:
      - db
    networks:
      - app_bamapas

  redis:
    container_name: redis_container
    image: redis
    depends_on:
      - app

networks:
  app_bamapas:
    name: app_bamapas
  db_network:
    name: db_network

volumes:
    db:
    app:
    pgadmin:
