version: "3"

services:

  db:
    container_name: db_container
    build:
      context: ./postgis
      dockerfile: Dockerfile
    env_file:
      - .env    
    ports:
      - "5432:5432"    
    volumes:
      - ./postgis/data/db:/var/lib/postgresql/data
    restart: unless-stopped
    
    networks:
      - db_network
    

  app:
    container_name: app_container
    build:
      context: ./app
      dockerfile: Dockerfile
    # command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - /bamapas:/opt/app
    depends_on:
      - db
    networks:
      - app_bamapas

  redis:
    container_name: redis_container
    image: redis
    depends_on:
      - app

networks:
  app_bamapas:
    name: app_bamapas
  db_network:
    name: db_network

volumes:
    db:
    app:
    pgadmin:
