version: "3"

services:

  nginx:
    container_name: nginx
    build:
      context: nginx/
      dockerfile: Dockerfile
    networks:
      - app_network
    restart: always
    expose:
      - 80
    ports:
      - 80:80


  db:
    container_name: db_container
    build:
      context: ./postgis
      dockerfile: Dockerfile
    env_file:
      - .env  
    ports:
      - 5432:5432
    volumes:
      - ./postgis/data/db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app_network

  app:
    container_name: app_container
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
      - 3000:3000
    depends_on:
      - db
    networks:
      - app_network

  redis:
    container_name: redis_container
    image: redis
    ports:
      - 6379:6379
    depends_on:
      - app
    env_file:
      - .env
    networks:
      - app_network
      
networks:
  app_network:
    driver: bridge

volumes:
    db:
    app: